name: 🔁 Send GitHub App Token Every 45 Min or Manual

on:
  workflow_dispatch:
  # Uncomment below to enable auto-schedule every 45 minutes
  # schedule:
  #   - cron: '*/45 * * * *'

jobs:
  send-token:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyJWT cryptography requests

      - name: Run token generator script
        env:
          APP_ID: ${{ secrets.APP_ID }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          LOGIC_APP_URL: ${{ secrets.LOGIC_APP_URL }}
        run: |
          python send_jwt.py
