name: 🟢 Start Logic App Job

on:
  workflow_dispatch:

jobs:
  run-main:
    runs-on: ubuntu-latest
    timeout-minutes: 100  # Automatically times out if too long

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create token refresh flag
        run: echo "true" > .token_refresh_enabled

      - name: Upload flag artifact
        uses: actions/upload-artifact@v4
        with:
          name: token-flag
          path: .token_refresh_enabled
          retention-days: 1

      - name: Trigger Logic App
        run: |
          curl -X POST ${{ secrets.LOGIC_APP_URL }}

      # Simulate a long-running task
      - name: Simulated long-running job
        run: sleep 5400  # Replace with actual job

      - name: Cleanup flag
        run: rm -f .token_refresh_enabled

      - name: Overwrite token flag to stop refresh
        uses: actions/upload-artifact@v4
        with:
          name: token-flag
          path: .github/empty.txt
